# Generated by Django 5.1.4 on 2024-12-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
    ]
