# Generated by Django 5.1.4 on 2024-12-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='profile',
        ),
    ]
