# Generated by Django 5.1.4 on 2024-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_fix_invalid_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
