# Generated by Django 5.1.4 on 2024-12-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blogpost_profile_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('food', 'Food'), ('travel', 'Travel')], default='technology', max_length=20),
        ),
    ]
