# Generated by Django 5.1.4 on 2025-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_flightbooking_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='destination',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
