# Generated by Django 5.1.4 on 2025-02-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_hotelbooking_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='FlightBooking',
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
