# Generated by Django 5.1.4 on 2025-03-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_hotel_city_hotelbooking_delete_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='activities',
            field=models.TextField(blank=True, default='Default activity'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='best_time_to_visit',
            field=models.TextField(blank=True, default='Default visit'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='group_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='itinerary',
            field=models.TextField(blank=True, default='Default plan'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='packing_checklist',
            field=models.TextField(blank=True, default='Default list'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='places_to_visit',
            field=models.TextField(blank=True, default='Default visit'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='restaurants',
            field=models.TextField(blank=True, default='Default visit'),
        ),
        migrations.DeleteModel(
            name='FlightBooking',
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
