# Generated by Django 5.1.4 on 2025-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_hotelbooking_user_travelplan_is_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='group_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends')], default='solo', max_length=10),
        ),
    ]
