# Generated by Django 5.1.4 on 2025-03-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_travelplan_budget_alter_travelplan_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='title',
        ),
    ]
