# Generated by Django 5.1.4 on 2025-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_travelplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='budget_breakdown',
            field=models.TextField(blank=True, default='Default budget'),
        ),
    ]
